### ISSUE TITLE
Merge with PAM_sqlite3?

### ISSUE THREAD

**Issue by q2dg** [agamez/libnss-sqlite3#1]
I think a common project using https://github.com/HormyAJP/pam_sqlite3 would be a great idea to have a self-contained, unified solution to get rid of /etc/passwd, /etc/shadow, /etc/group in order to be able to login into a Linux system.
Thanks!

**Comment by agamez** [comment]
Hi!

I wouldn't mind that at all, but truth is I haven't had any use for libnss-sqlite3 for years now, so I don't really have the time to spend on that. pam_sqlite3 seems to be as maintained as libnss-sqlite3 as well, which is very little, so I don't know if its developer would be willing to spend that time either.

I'm all for merging both projects though, so in that sense you have my blessing and the little help I could provide, given that I don't really remember what I even used this for :D

Best regards!

**Comment by q2dg** [comment]
Thanks a lot for your frankness.
So I'll close the issue in this case, if you don't mind.

I haven't the required technical skills to do the merging but I'll try, anyway. 
If I get it, don't doubt that I will let you know.
Thanks!
